# Generated by Django 6.0.5 on 2026-06-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topicfollow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='messages',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='base.messages'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
